# Generated by Django 3.0 on 2019-12-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rn', models.CharField(max_length=15)),
                ('div', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=30)),
                ('sscm', models.DecimalField(decimal_places=4, max_digits=6)),
                ('hscm', models.DecimalField(decimal_places=4, max_digits=6)),
                ('fe_cgpa', models.DecimalField(decimal_places=4, max_digits=6)),
                ('se_cgpa', models.DecimalField(decimal_places=4, max_digits=6)),
                ('te_cgpa', models.DecimalField(decimal_places=4, max_digits=6)),
            ],
        ),
    ]
