# Generated by Django 3.0 on 2020-04-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0004_auto_20200421_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='be1_tot_credits',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='be1_tot_credits_obtained',
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='be2_tot_credits',
            field=models.IntegerField(default=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='be2_tot_credits_obtained',
            field=models.IntegerField(default=23),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='diploma_percentage',
            field=models.FloatField(default=90.8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='xiith_percentage',
            field=models.FloatField(default=82.31),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='xth_percentage',
            field=models.FloatField(default=90.8),
            preserve_default=False,
        ),
    ]
