# Generated by Django 3.0 on 2020-04-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_register', '0007_studentprofile_engg_cgpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='placed',
            field=models.BooleanField(default=False),
        ),
    ]
